### PR TITLE
Possibility of infinite retrying via :tries=>0

### PR DESCRIPTION
**Pull request by Nakilon**
For infinite sequence of intervals had to use Enumerator.  
Maybe get rid of Array at all? That would eliminate few `if`s that check if `tries` is zero.

Note: `!!` sure makes sense in Ruby but not in `if` condition.

### CODE REVIEW

**Comment by kamui** [comment]
I'm wondering if `0` makes sense as representing infinity. I think it might be confusing and unintuitive. Maybe `Float::INFINITY`?

**Comment by apurvis** [comment]
> Maybe `Float::INFINITY`?

+1 to that idea

**Comment by pchaganti** [comment]
👍

**Comment by apurvis** [comment]
I feel like the issue of infinite retries is better solved with some simple input validation to make sure `tries > 0` (or `!intervals.empty?`).

the idea of allowing an enumerator is not a bad one but sort of deserves a separate PR.

**Comment by kamui** [comment]
Closing this PR since using 0 tries not the approach we want.

**Pull request closed without merging**
