### PR TITLE
New feature: configurable environments

### PR DESCRIPTION
**Pull request by apurvis**
Before we settled on using `Retriable`, we had our own gem for retries called [Pester](https://github.com/lumoslabs/pester).  We went with `Retriable` in the end but there was one killer feature of `Pester` that we have long wanted in `Retriable` so we added it.

The documentation should explain things but let me know if anything is unclear

@kamui / @slpsys

### CODE REVIEW

**Comment by pchaganti** [comment]
This seems like a really neat thing to add to retriable. Nice work.

👍

**Comment by kamui** [comment]
Thanks for taking the time to create a PR for this feature. I've been thinking about it since you submitted it and the main thing I've been wondering is whether this is really needs to be supported in the library. If you wanted something like this, you could just define wrappers:

```
def retriable_aws(&block)
  Retriable.retriable(max_attempts: 3, delay_interval: 5, &block)
end

def retriable_mysql(&block)
  Retriable.retriable(max_attempts: 2, delay_interval: 0, &block)
end
```

It would also give you the flexibility to define different method arguments, or maybe you put this in a global hash or define your own singleton, maybe you only want it scoped to a certain part of your app or class instead of global, you could define if you want the caller to override the per context defaults or not, etc.

I could see value in adding examples in the README for how to create your own wrappers.

**Comment by slpsys** [comment]
I definitely understand that it could be an overreach for the library, and there _should_ be a very hard, "Does the library need this?" question posed any time scope increases. That said, the reason we're using a retry library is to concentrate and coordinate logic for heterogenous environments (typically for network calls intra-VPC, intra-AZ, intra-cloud, et al. or for...crappy services), and this seemed like the most elegant solution, at least from the config and caller perspective. 

Barring that, in the scope of a full application I'd probably advocate something like [SimpleDelegator](https://ruby-doc.org/stdlib-2.2.1/libdoc/delegate/rdoc/SimpleDelegator.html) or a similar decorator class over `Retriable`, instead of `def` wrappers. Minor difference, but more along the lines we were originally thinking.

As an aside, apologies if this isn't even the best way to propose a new feature, we just already had it written for Pester, etc.

**Comment by apurvis** [comment]
Here's how I see it:

1. putting methods in the global namespace of an app is generally regarded as not a great idea.
2. one could instead maybe at least encapsulate these kinds of methods in a module or something - `LocalRetriable` if you will, and then your app could use `LocalRetriable.retry_aws` or whatever.
3. from my perspective, the disadvantage of the `LocalRetriable.retry_aws` approach is that it doesn't really encourage any kind of standardization, which is worth something - and IMHO it's worth enough to add a feature to an otherwise pretty bare bones library.  

I think that's ultimately the main pro/con argument - it adds a "complication", if you will, but at the same time it encourages users to have a consistent approach for `Retriable` calls across their applications.  given that i think a lot of people end up with cross application use cases - `Retriable.mysql` and `Retriable.aws` immediately come to mind in our situation - I feel like encouraging a good solution to a common problem isn't quite out of scope for what the gem could support.

**Comment by apurvis** [comment]
i would add that the `complication` is really just a pretty simple implementation of how to call existing `Retriable` code - there's no hacking in the main gem code to support this/it's basically totally standalone code.  IMHO that makes the "complication" significantly less of a "con" argument because there's no actual resulting complication in the core code.

**Comment by apurvis** [comment]
@kamui any thoughts/decisions in the past 2 weeks?

**Comment by kamui** [comment]
@slpsys Agreed, `SimpleDelegator` would be a good way to accomplish this too.

I do appreciate the PR and you guys wanting to improve the library.

**Comment by apurvis** [comment]
not sure what that means, but if you would rather not have the feature, close this PR and we'll just fork our own version.

**Comment by apurvis** [comment]
(or leave it open if you want; see if any other feedback comes in besides @pchaganti)

**Comment by kamui** [comment]
@apurvis:

Yeah, I didn't mean to advocate putting methods in the global namespace. I just left out the class/module definition as an exercise for the user to figure out where they would want those methods to live.. I'd definitely recommend putting it in a module or class.

I do this this feature is out of scope for this library, I'd rather the user figure out how they want to define helper methods for different contexts.

I'd be more willing to merge a PR like this that was opt in. So you don't get it by default, but if you want it, you have to require an extension that adds this functionality. The current API might have to change a bit, or not. Similar to how the kernel extension that makes it a global method is an opt in feature.

**Comment by apurvis** [comment]
That's not a bad idea; maybe i can move it to a separate `lib/retriable_environments` folder in such a way that you have to do 
```ruby
require 'retriable'
require 'retriable_environments'
```

**Comment by kamui** [comment]
That approach would work for me. Before you start down this approach, maybe we can have a discussion about namespacing and the usage api for this feature.

I'm wondering if `environments` is a good name, since in Rails it's a bit loaded and users might confuse it with `development`, `staging`, `production` environments. I'm not sure if I have a better name, maybe context or scope?

**Comment by apurvis** [comment]
sorry just saw this message - that's a good point re: namespacing.  `contexts` is a lot better.   maybe continue the discussion on [the other PR](https://github.com/kamui/retriable/issues/29)?

**Comment by apurvis** [comment]
closing in favor of https://github.com/kamui/retriable/issues/29

**Pull request closed without merging**
