### PR TITLE
Organize MiniTest tests to pass on JRuby - WIP stalled

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR tries to make minitest runs work correctly on JRuby.

- use built-in minitest, calling `ruby` directly
- require relative each of the tests in `spec/test_all.rb`
- include the DSL in each of the tests
- require the minitest/spec in the helper

All of this makes the tests pass!

That made me take away ruby-head and jruby-head from the allow_failures.

**Update**: I can't get MiniTest to do the right thing here. The commits list shows my tragic path.

### CODE REVIEW

**Comment by apurvis** [comment]
we should really be using rspec :(

**Comment by apurvis** [comment]
i've thought about it but sort of concluded i don't really have the time.  it's a big change and i'm not even sure @kamui is on board with it.

**Comment by kamui** [comment]
@olleolleolle Thanks for the attempt.

I do personally prefer minitest for the simplicity, but I'm not dogmatic about it vs rspec. If someone is interested in doing a port of the current spec suite in rspec, I'd be on board with merging it. It would be some work though and I'm unsure if it'd be worth the trouble for jruby spec coverage, even though it'd be nice.

**Comment by apurvis** [comment]
@kamui you can probably close this PR now

**Pull request closed without merging**
