### PR TITLE
Add on_max_elapsed_time callback

### PR DESCRIPTION
**Pull request by jcobian**
Solves #76

### CODE REVIEW

**Comment by jcobian** [comment]
Travis is currently failing b/c of a rubygems issue but that should be fixed once #75 is merged

Also this will have merge conflicts with #73 if we decide to merge that PR as well.

FWIW, I actually prefer/would like this proposal about max elapsed time more so than the `on_final_failure` one.

Up to you all but happy to discuss more!

**Comment by jcobian** [comment]
@apurvis what do you think about this? Sorry for a flurry of PRs at once. However, this gem is great and has been super easy to contribute to!

**Comment by jcobian** [comment]
@kamui or should I tag you? Apologies, not sure what the correct process is or who to tag

**Comment by kamui** [comment]
Thanks for this contribution. It's on my list of things to do. I'll try to get to it by this weekend!

**Comment by jcobian** [comment]
> Thanks for this contribution. It's on my list of things to do. I'll try to get to it by this weekend!

Awesome, no rush. Thank you!

**Comment by apurvis** [comment]
lgtm but @kamui holds the keys here; i'm just a contributor of some features

**Comment by apurvis** [comment]
@kamui usually handles bumping the version numbers but i guess this should be 3.2.0

**Comment by kamui** [comment]
This feature makes sense to me, but give me some time to think about this approach.

**Comment by jcobian** [comment]
going to close this out.

**Pull request closed without merging**
